#!/bin/bash
rm -rf kirby_rebuilt.nes
ca65 -o example.o -g src/main.asm -t nes
ld65 -Ln linked.txt -C linker.cfg -o kirby_rebuilt.nes --dbgfile linked_m.dbg example.o
rm -rf example.o
rm -rf kirby_rebuilt.nes.deb

python3 tools/checksum.py