mus_vegetable_valley_pulse2:
MUS_TEMPO 1
MUS_PLAY $A16E
MUS_UNK_F0 $0D
.byte $F4,$F0
PAT_ENV1 $1E
.byte $34
.byte $F1
.byte $FC,$F6,$21
.byte $F4,$82
PAT_REPEAT 7
.byte $2A
PAT_ENDREPEAT
MUS_PLAY $A16E
MUS_PLAY $A196
MUS_TEMPO 1
@loop:
MUS_PLAY $A16E
MUS_PLAY $A1BB
MUS_PLAY $A16E
MUS_PLAY $A1D4
PAT_TRANSPOSE $11
MUS_PLAY $A2D7
PAT_TRANSPOSE $14
MUS_PLAY $A2D7
PAT_TRANSPOSE $11
MUS_PLAY $A2D7
MUS_PLAY $A1FD
PAT_TRANSPOSE $11
MUS_PLAY $A0ED
MUS_UNK_F0 $0D
MUS_PLAY $A154
MUS_PLAY $A0ED
MUS_PLAY $A12F
PAT_TRANSPOSE $11
MUS_PLAY $A258
PAT_TRANSPOSE $14
MUS_PLAY $A258
PAT_TRANSPOSE $11
MUS_PLAY $A258
MUS_PLAY $A29D
MUS_LOOP @loop

incbinRange "../split/prg/bank1e.bin", $ED, $301
mus_vegetable_valley_noise:
MUS_TEMPO 1
PAT_REPEAT 7
MUS_PLAY $A350
PAT_ENDREPEAT
MUS_PLAY $A335
MUS_TEMPO 1
@loop:
PAT_REPEAT 3
MUS_PLAY $A350
PAT_ENDREPEAT
MUS_PLAY $A335
PAT_REPEAT 3
MUS_PLAY $A350
PAT_ENDREPEAT
MUS_PLAY $A335
PAT_REPEAT 7
MUS_PLAY $A350
PAT_ENDREPEAT
MUS_PLAY $A335
PAT_REPEAT 15
MUS_PLAY $A350
PAT_ENDREPEAT
MUS_PLAY $A335
MUS_LOOP @loop

incbinRange "../split/prg/bank1e.bin", $335, $367

mus_vegetable_valley_triangle:
MUS_TEMPO 1
.byte $F5,$29
MUS_PLAY $A47D
MUS_PLAY $A47D
.byte $F5,$2B
MUS_PLAY $A47D
.byte $F5,$29
PAT_REPEAT 3
MUS_PLAY $A47D
PAT_ENDREPEAT
.byte $F5,$2B
MUS_PLAY $A47D
.byte $F5,$29
MUS_PLAY $A489
MUS_TEMPO 1
.byte $F5,$29
MUS_PLAY $A47D
MUS_PLAY $A47D
.byte $F5,$2B
MUS_PLAY $A47D
.byte $F5,$29
MUS_PLAY $A4A6
.byte $F5,$29
MUS_PLAY $A47D
MUS_PLAY $A47D
.byte $F5,$2B
MUS_PLAY $A47D
.byte $F5,$29
MUS_PLAY $A496
.byte $F5,$29
.byte $F4,$78
MUS_PLAY $A472
.byte $F5,$2C
MUS_PLAY $A472
.byte $F5,$29
MUS_PLAY $A472
MUS_PLAY $A45F
.byte $F4,$A0,$7E
.byte $F5,$29
MUS_PLAY $A42B
MUS_PLAY $A452
MUS_PLAY $A42B
MUS_PLAY $A442
.byte $F5,$35
MUS_PLAY $A3E4
MUS_PLAY $A415
MUS_PLAY $A3E4
MUS_PLAY $A3FF
.byte $F8,$8A,$A3
incbinRange "../split/prg/bank1e.bin", $3e4, $4b6

mus_vegetable_valley_pulse1:
MUS_TEMPO 1
MUS_PLAY @PATTERN1
MUS_TEMPO 1
@loop:
PAT_SETTINGS $07
PAT_ENV1 $24
MUS_PLAY @PATTERN2
MUS_PLAY @PATTERN4
MUS_PLAY @PATTERN8
MUS_PLAY @PATTERN9
PAT_ENV1 $24
MUS_PLAY @PATTERN3
MUS_PLAY @PATTERN4
MUS_PLAY @PATTERN5
MUS_PLAY @PATTERN6
PAT_SETTINGS $07
PAT_ENV1 $24
MUS_PLAY @PATTERN11
PAT_ENV1 $24
MUS_PLAY @PATTERN12
PulseNote PULSE_QUARTER, 0, 4 ; F#5
PAT_SETTINGS $07
PAT_ENV1 $22
MUS_PLAY @PATTERN2
MUS_PLAY @PATTERN4
MUS_PLAY @PATTERN8
MUS_PLAY @PATTERN10
PAT_ENV1 $22
MUS_PLAY @PATTERN3
MUS_PLAY @PATTERN4
MUS_PLAY @PATTERN5
MUS_PLAY @PATTERN7
PAT_SETTINGS $07
PAT_ENV1 $0F
MUS_PLAY @PATTERN11
PAT_ENV1 $0F
MUS_PLAY @PATTERN12
;rest ?
PulseNote PULSE_QUARTER, 1, 0 ; A#3
MUS_LOOP @loop

@PATTERN1:
;settings
PAT_SETTINGS $07
;envelope settings??
@goonga:
PAT_ENV1 $0F
PAT_TRANSPOSE $29
PAT_ENV3 $7D

PAT_REPEAT 5
PulseNote PULSE_EIGHTH, 1, 9 ; G4
PulseNote PULSE_EIGHTH, 1, 11 ; A4
PulseNote PULSE_EIGHTH, 0, 0 ; D5
PAT_ENDREPEAT

PulseNote PULSE_SIXTEENTH, 1, 9 ; G4
PulseNote PULSE_SIXTEENTH, 1, 9 ; G4

PAT_REPEAT 3
PulseNote PULSE_EIGHTH, 1, 11 ; A4
PulseNote PULSE_EIGHTH, 1, 14 ; C5
PulseNote PULSE_EIGHTH, 0, 5 ; G5
PAT_ENDREPEAT

PulseNote PULSE_EIGHTH, 1, 11 ; A4
PulseNote PULSE_EIGHTH, 1, 14 ; C5
PulseNote PULSE_EIGHTH, 0, 2 ; E5
PulseNote PULSE_EIGHTH, 0, 4 ; F#5
PAT_ENV3 $FA
PAT_UNKF1 $FF
PAT_TRANSPOSE $35
PulseNote PULSE_SIXTEENTH, 0, 0 ; D5
PAT_UNKF1 $FD
PulseNote PULSE_SIXTEENTH, 0, 0 ; D5
PAT_UNKF1 $03
PulseNote PULSE_SIXTEENTH, 0, 12 ; D6
PAT_UNKF1 $FD
PulseNote PULSE_SIXTEENTH, 0, 12 ; D6
PAT_UNKF1 $03
PulseNote PULSE_SIXTEENTH, 0, 0 ; D5
PAT_UNKF1 $FD
PulseNote PULSE_SIXTEENTH, 0, 0 ; D5
PAT_UNKF1 $03
PAT_ENV1 $0F
PAT_ENV3 $7D
PAT_TRANSPOSE $29
PAT_SETTINGS $07

PAT_REPEAT 5
PulseNote PULSE_EIGHTH, 1, 9 ; G4
PulseNote PULSE_EIGHTH, 1, 11 ; A4
PulseNote PULSE_EIGHTH, 0, 0 ; D5
PAT_ENDREPEAT

PulseNote PULSE_SIXTEENTH, 1, 9 ; G4
PulseNote PULSE_SIXTEENTH, 1, 9 ; G4
PulseNote PULSE_EIGHTH, 1, 11 ; A4
PAT_UNKF1 $FF
PulseNote PULSE_EIGHTH, 1, 13 ; B4
PulseNote PULSE_EIGHTH, 1, 14 ; C5
PulseNote PULSE_EIGHTH, 0, 2 ; E5
PulseNote PULSE_EIGHTH, 0, 5 ; G5
PulseNote PULSE_EIGHTH, 0, 2 ; E5
PulseNote PULSE_EIGHTH, 0, 5 ; G5
PulseNote PULSE_EIGHTH, 0, 9 ; B5
PulseNote PULSE_EIGHTH, 0, 7 ; A5
PAT_ENV1 $04
PAT_UNKF1 $02
PAT_ENV3 $6E
PulseNote PULSE_EIGHTH, 0, 12 ; D6
PulseNote PULSE_EIGHTH, 0, 10 ; C6
PAT_ENV3 $C8
PulseNote PULSE_EIGHTH, 0, 9 ; B5
PAT_ENV3 $78
PulseNote PULSE_EIGHTH, 0, 7 ; A5
; rest???
PulseNote PULSE_DQUARTER, 1, 0 ; A#3
PAT_END

@PATTERN2:
PAT_TRANSPOSE $29
PAT_ENV3 $FF
PulseNote PULSE_DQUARTER, 1, 13 ; B4
PulseNote PULSE_SIXTEENTH, 1, 14 ; C5
PulseNote PULSE_SIXTEENTH, 0, 0 ; D5
PAT_END

@PATTERN3:
PAT_TRANSPOSE $29
PAT_ENV3 $FF
PulseNote PULSE_DQUARTER, 0, 0 ; D5
PulseNote PULSE_SIXTEENTH, 1, 13 ; B4
PulseNote PULSE_SIXTEENTH, 0, 0 ; D5
PAT_END

@PATTERN4:
PulseNote PULSE_QUARTER, 0, 7 ; A5
PulseNote PULSE_QUARTER, 0, 5 ; G5
PulseNote PULSE_QUARTER, 0, 4 ; F#5
PulseNote PULSE_DEIGHTH, 0, 2 ; E5
PulseNote PULSE_SIXTEENTH, 0, 4 ; F#5
PulseNote PULSE_QUARTER, 0, 0 ; D5
PAT_END

@PATTERN5:
PulseNote PULSE_QUARTER, 0, 5 ; G5
PulseNote PULSE_DQUARTER, 0, 7 ; A5
PulseNote PULSE_SIXTEENTH, 0, 8 ; A#5
PulseNote PULSE_SIXTEENTH, 0, 9 ; B5
PulseNote PULSE_QUARTER, 0, 10 ; C6
PulseNote PULSE_DEIGHTH, 0, 14 ; E6
PulseNote PULSE_SIXTEENTH, 0, 12 ; D6
PulseNote PULSE_CUSTOM, 0, 12, 40 ; D6
PAT_END

@PATTERN6:
PulseNote PULSE_EIGHTH, 1, 0 ; A#3
PAT_TRANSPOSE $29
PAT_SETTINGS $05
PAT_ENV1 $07
PulseNote PULSE_SIXTEENTH, 0, 10 ; C6
PulseNote PULSE_SIXTEENTH, 0, 10 ; C6
PulseNote PULSE_EIGHTH, 0, 10 ; C6
PulseNote PULSE_EIGHTH, 1, 0 ; A#3
PAT_END

@PATTERN7:
PulseNote PULSE_SIXTEENTH, 1, 0 ; A#3
PAT_TRANSPOSE $1D
PAT_SETTINGS $06
PAT_ENV3 $FC
PAT_ENV1 $21
PulseNote PULSE_SIXTEENTH, 0, 0 ; D5
PAT_ENV3 $AB
PulseNote PULSE_SIXTEENTH, 0, 2 ; E5
PulseNote PULSE_SIXTEENTH, 0, 3 ; F5
PulseNote PULSE_SIXTEENTH, 0, 4 ; F#5
PulseNote PULSE_SIXTEENTH, 1, 14 ; C5
PulseNote PULSE_EIGHTH, 0, 10 ; C6
PAT_END

@PATTERN8:
PulseNote PULSE_QUARTER, 1, 13 ; B4
PulseNote PULSE_DQUARTER, 1, 14 ; C5
PulseNote PULSE_SIXTEENTH, 0, 2 ; E5
PulseNote PULSE_SIXTEENTH, 0, 5 ; G5
PulseNote PULSE_QUARTER, 0, 12 ; D6
PulseNote PULSE_DEIGHTH, 0, 10 ; C6
PulseNote PULSE_SIXTEENTH, 0, 9 ; B5
PulseNote PULSE_CUSTOM, 0, 7, 40 ; A5
PAT_END

@PATTERN9:
PulseNote PULSE_EIGHTH, 1, 0 ; A#3
PAT_TRANSPOSE $35
PAT_ENV1 $21
PAT_ENV3 $A0
PAT_UNKF1 $FE
PulseNote PULSE_SIXTEENTH, 0, 7 ; A5
PulseNote PULSE_SIXTEENTH, 0, 7 ; A5
PulseNote PULSE_SIXTEENTH, 0, 4 ; F#5
PAT_UNKF1 $02
PulseNote PULSE_DEIGHTH, 1, 0 ; A#3
PAT_END

@PATTERN10:
PulseNote PULSE_EIGHTH, 1, 0 ; A#3
PAT_TRANSPOSE $35
PAT_ENV1 $21
PAT_ENV3 $A0
PAT_UNKF1 $FE
PulseNote PULSE_SIXTEENTH, 0, 7 ; A5
PAT_UNKF1 $FF
PulseNote PULSE_SIXTEENTH, 0, 7 ; A5
PAT_UNKF1 $02
PulseNote PULSE_SIXTEENTH, 0, 12 ; D6
PAT_UNKF1 $03
PulseNote PULSE_DEIGHTH, 1, 0 ; A#3
PAT_END

@PATTERN11:
PAT_TRANSPOSE $35
PAT_ENV3 $FA
PulseNote PULSE_DEIGHTH, 1, 10 ; G#4
PulseNote PULSE_SIXTEENTH, 1, 12 ; A#4
PulseNote PULSE_SIXTEENTH, 1, 13 ; B4
PulseNote PULSE_SIXTEENTH, 1, 0 ; A#3
PulseNote PULSE_SIXTEENTH, 0, 6 ; G#5
PulseNote PULSE_SIXTEENTH, 1, 0 ; A#3
PulseNote PULSE_QUARTER, 0, 4 ; F#5
PulseNote PULSE_DEIGHTH, 1, 15 ; C#5
PulseNote PULSE_SIXTEENTH, 0, 1 ; D#5
PulseNote PULSE_QUARTER, 0, 2 ; E5
PulseNote PULSE_DEIGHTH, 1, 13 ; B4
PulseNote PULSE_SIXTEENTH, 0, 2 ; E5
PulseNote PULSE_CUSTOM, 1, 12, 40 ; A#4
PulseNote PULSE_DEIGHTH, 1, 13 ; B4
PulseNote PULSE_SIXTEENTH, 1, 15 ; C#5
PulseNote PULSE_SIXTEENTH, 0, 0 ; D5
PulseNote PULSE_SIXTEENTH, 1, 0 ; A#3
PulseNote PULSE_SIXTEENTH, 0, 9 ; B5
PulseNote PULSE_SIXTEENTH, 1, 0 ; A#3
PulseNote PULSE_QUARTER, 0, 7 ; A5
PulseNote PULSE_DEIGHTH, 0, 5 ; G5
PulseNote PULSE_SIXTEENTH, 0, 4 ; F#5
PulseNote PULSE_DQUARTER, 0, 2 ; E5
PAT_ENV1 $04
PAT_ENV3 $00
PAT_TRANSPOSE $41
PAT_UNKF1 $FD
PulseNote PULSE_SIXTEENTH, 0, 7 ; A5
PAT_UNKF1 $FE
PulseNote PULSE_SIXTEENTH, 0, 7 ; A5
PAT_UNKF1 $02
PulseNote PULSE_SIXTEENTH, 1, 11 ; A4
PAT_UNKF1 $FE
PulseNote PULSE_SIXTEENTH, 1, 11 ; A4
PAT_UNKF1 $05
PulseNote PULSE_DQUARTER, 1, 0 ; A#3
PAT_TRANSPOSE $35
PAT_END

@PATTERN12:
PAT_ENV3 $FA
PulseNote PULSE_DEIGHTH, 1, 10 ; G#4
PulseNote PULSE_SIXTEENTH, 1, 11 ; A4
PulseNote PULSE_SIXTEENTH, 1, 13 ; B4
PulseNote PULSE_SIXTEENTH, 1, 0 ; A#3
PulseNote PULSE_EIGHTH, 0, 6 ; G#5
PulseNote PULSE_DQUARTER, 0, 4 ; F#5
PulseNote PULSE_SIXTEENTH, 1, 15 ; C#5
PulseNote PULSE_SIXTEENTH, 0, 1 ; D#5
PulseNote PULSE_QUARTER, 0, 2 ; E5
PulseNote PULSE_DEIGHTH, 1, 13 ; B4
PulseNote PULSE_SIXTEENTH, 0, 2 ; E5
PulseNote PULSE_QUARTER, 1, 12 ; A#4
PulseNote PULSE_SIXTEENTH, 1, 13 ; B4
PulseNote PULSE_SIXTEENTH, 1, 0 ; A#3
PulseNote PULSE_SIXTEENTH, 1, 15 ; C#5
PulseNote PULSE_SIXTEENTH, 1, 0 ; A#3
PulseNote PULSE_DEIGHTH, 0, 0 ; D5
PulseNote PULSE_SIXTEENTH, 0, 2 ; E5
PulseNote PULSE_SIXTEENTH, 0, 4 ; F#5
PulseNote PULSE_SIXTEENTH, 1, 0 ; A#3
PulseNote PULSE_SIXTEENTH, 0, 12 ; D6
PulseNote PULSE_SIXTEENTH, 1, 0 ; A#3
PulseNote PULSE_EIGHTH, 0, 11 ; C#6
PulseNote PULSE_EIGHTH, 1, 0 ; A#3
PulseNote PULSE_QUARTER, 0, 6 ; G#5
PulseNote PULSE_CUSTOM, 0, 7, 40 ; A5
PulseNote PULSE_QUARTER, 1, 0 ; A#3
PAT_ENV1 $0F
PAT_SETTINGS $06
PAT_ENV3 $BE
PAT_TRANSPOSE $1D
PAT_END

mus_vegetable_valley_dpcm:
MUS_TEMPO 1
PAT_REPEAT 4
MUS_PLAY @PATTERN4
.byte $FD
@loop:
MUS_TEMPO 1
PAT_REPEAT 2
MUS_PLAY @PATTERN4
MUS_PLAY @PATTERN5
.byte $FD
MUS_PLAY @PATTERN6
MUS_PLAY @PATTERN7
MUS_PLAY @PATTERN6
MUS_PLAY @PATTERN8
MUS_PLAY @PATTERN4
MUS_PLAY @PATTERN3
MUS_PLAY @PATTERN4
PAT_REPEAT 3
PAT_SAMPLE kick_Start, kick_End
.byte $7F
PAT_SAMPLE snare_Start, snare_End
.byte $7F
.byte $FD
PAT_SAMPLE kick_Start, kick_End
.byte $9F
PAT_SAMPLE snare_Start, snare_End
.byte $3F
PAT_REPEAT 3
MUS_PLAY @PATTERN1
MUS_PLAY @PATTERN2
.byte $FD
MUS_PLAY @PATTERN1
PAT_SAMPLE kick_Start, kick_End
.byte $7F
PAT_SAMPLE snare_Start, snare_End
.byte $3F
PAT_SAMPLE kick_Start, kick_End
.byte $3F,$7F
PAT_SAMPLE snare_Start, snare_End
.byte $3F
PAT_SAMPLE kick_Start, kick_End
.byte $3F
MUS_LOOP @loop

@PATTERN1:
PAT_REPEAT 2
PAT_SAMPLE kick_Start, kick_End
.byte $7F
PAT_SAMPLE snare_Start, snare_End
.byte $3F
PAT_SAMPLE kick_Start, kick_End
.byte $3F
.byte $FD
PAT_END

@PATTERN2:
.byte $7F
PAT_SAMPLE snare_Start, snare_End
.byte $3F
PAT_SAMPLE kick_Start, kick_End
.byte $7F,$3F
PAT_SAMPLE snare_Start, snare_End
.byte $7F
PAT_END

@PATTERN3:
PAT_REPEAT 3
PAT_SAMPLE kick_Start, kick_End
.byte $7F
PAT_SAMPLE snare_Start, snare_End
.byte $7F
.byte $FD
PAT_SAMPLE kick_Start, kick_End
.byte $3F,$3F
PAT_SAMPLE snare_Start, snare_End
.byte $7F
PAT_END

@PATTERN4:
PAT_REPEAT 3
PAT_SAMPLE kick_Start, kick_End
.byte $7F
PAT_SAMPLE snare_Start, snare_End
.byte $7F
.byte $FD
PAT_SAMPLE kick_Start, kick_End
.byte $7F
PAT_SAMPLE snare_Start, snare_End
.byte $3F
PAT_SAMPLE kick_Start, kick_End
.byte $3F
PAT_END

@PATTERN5:
PAT_REPEAT 3
PAT_SAMPLE kick_Start, kick_End
.byte $7F
PAT_SAMPLE snare_Start, snare_End
.byte $7F
.byte $FD
PAT_SAMPLE kick_Start, kick_End
.byte $9F,$3F
PAT_END

@PATTERN6:
PAT_REPEAT 3
PAT_SAMPLE kick_Start, kick_End
.byte $7F
PAT_SAMPLE snare_Start, snare_End
.byte $7F
PAT_SAMPLE kick_Start, kick_End
.byte $3F,$3F
PAT_SAMPLE snare_Start, snare_End
.byte $7F
.byte $FD
PAT_END

@PATTERN7:
PAT_SAMPLE kick_Start, kick_End
.byte $7F
PAT_SAMPLE snare_Start, snare_End
.byte $3F
PAT_SAMPLE kick_Start, kick_End
.byte $7F,$3F
PAT_SAMPLE snare_Start, snare_End
.byte $3F
PAT_SAMPLE kick_Start, kick_End
.byte $1F
PAT_SAMPLE snare_Start, snare_End
.byte $1F
PAT_END

@PATTERN8:
PAT_REPEAT 2
PAT_SAMPLE kick_Start, kick_End
.byte $3F
PAT_SAMPLE snare_Start, snare_End
.byte $3F
.byte $FD,$7F
PAT_SAMPLE kick_Start, kick_End
.byte $3F,$1F,$1F
PAT_END